# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ release/rel_3 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 22
      uses: actions/setup-java@v1
      with:
        java-version: 22
    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: >
        mvn -B verify -P integration-tests
        -Dintegration.thetvdb.com.v3.apikey=$APIKEY
        -Dintegration.thetvdb.com.v3.userkey=$USERKEY
        -Dintegration.thetvdb.com.v3.username=$USERNAME
      env:
        APIKEY: ${{ secrets.THETVDB_V3_APIKEY }}
        USERKEY: ${{ secrets.THETVDB_V3_USERKEY }}
        USERNAME: ${{ secrets.THETVDB_V3_USERNAME }}
